share_search/reviews/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from reviews.views import (StoreDetailView, StoreListView,
                           StoreUpdateView, ProductListView,
                           ProductDetailView, StoreCreateView,
                           PhotoModelCreateView,
                           ProductCreateView, ProductUpdateView)


urlpatterns = patterns(
    '',
    url(r'^stores/$', StoreListView.as_view(), name="store_list"),
    url(r'^stores/(?P<pk>\d+)/$', StoreDetailView.as_view(), name="store"),
    url(
        r'^stores/edit/(?P<pk>\d+)/$',
        StoreUpdateView.as_view(),
        name="store_edit"
    ),
    url(
        r'^products/edit/(?P<pk>\d+)/$',
        ProductUpdateView.as_view(),
        name="product_edit"
    ),
    url(r'^stores/create/$', StoreCreateView.as_view(), name="store"),
    url(r'^products/$', ProductListView.as_view(template_name="reviews/products.html"), name="product_list"),
    url(r'^products/$', TemplateView.as_view(template_name="reviews/products.html"), name="product_list"),
    url(r'^stores/create/$', StoreCreateView.as_view(), name="store_create"),
    url(r'^products/create/$', ProductCreateView.as_view(), name="product_create"),
    url(
        r'^products/(?P<pk>\d+)/$',
        ProductDetailView.as_view(),
        name="product",
    ),
    url(
        r'^photos/create/$',
        PhotoModelCreateView.as_view(),
        name="photo_create"
    ),
)

share_search/share_search/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
    '',
    url(
        r'^$',
        TemplateView.as_view(template_name="semi_static/home.html"),
        name="home"
    ),
    url(r'', include('share_site.urls', namespace="site")),
    url(r'', include('reviews.urls', namespace="reviews")),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

share_search/templates/_layouts/base.html
<!doctype html>
<html>
    <head>
        <title>{% block title %}Share Search{% endblock %}</title>
        <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="{{ STATIC_URL }}css/app.css" rel="stylesheet" type="text/css">
        <script src="{{ STATIC_URL }}js/jquery-1.9.1.min.js"></script>
        <script src="{{ STATIC_URL }}js/jquery.masonry.min.js"></script>
        <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
        <script src="{{ STATIC_URL }}js/app.js"></script>
    </head>
    <body>
        <div class="container">
            <div class="navbar">
                <div class="navbar-inner">
                    <a href="{% url "home" %}" class="brand">
                        <img src="{{ STATIC_URL }}img/logo.png">
                    </a>
                    <ul class="nav">
                        <li><a href="{% url "reviews:store_list" %}">Stores</a></li>
                        <li><a href="{% url "reviews:product_list" %}">Products</a></li>
                    </ul>
                    <ul class="nav pull-right">
                        {% if user.is_authenticated %}
                            <li><a href="{% url "site:logout" %}">Log Out</a></li>
                        {% else %}
                            <li><a href="{% url "site:login" %}">Log In</a></li>
                            <li><a href="{% url "site:register" %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>