share_search/reviews/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from reviews.views import (StoreDetailView, StoreListView,
                           StoreUpdateView, ProductListView,
                           ProductDetailView, StoreCreateView,
                           PhotoModelCreateView,
                           ProductCreateView, ProductUpdateView)


urlpatterns = patterns(
    '',
    url(r'^stores/$', StoreListView.as_view(), name="store_list"),
    url(r'^stores/(?P<pk>\d+)/$', StoreDetailView.as_view(), name="store"),
    url(
        r'^stores/edit/(?P<pk>\d+)/$',
        StoreUpdateView.as_view(),
        name="store_edit"
    ),
    url(
        r'^products/edit/(?P<pk>\d+)/$',
        ProductUpdateView.as_view(),
        name="product_edit"
    ),
    url(r'^stores/create/$', StoreCreateView.as_view(), name="store"),
    url(r'^products/$', ProductListView.as_view(template_name="reviews/products.html"), name="product_list"),
    url(r'^products/$', TemplateView.as_view(template_name="reviews/products.html"), name="product_list"),
    url(r'^stores/create/$', StoreCreateView.as_view(), name="store_create"),
    url(r'^products/create/$', ProductCreateView.as_view(), name="product_create"),
    url(
        r'^products/(?P<pk>\d+)/$',
        ProductDetailView.as_view(),
        name="product",
    ),
    url(
        r'^photos/create/$',
        PhotoModelCreateView.as_view(),
        name="photo_create"
    ),
)

share_search/share_search/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns(
    '',
    url(
        r'^$',
        TemplateView.as_view(template_name="semi_static/home.html"),
        name="home"
    ),
    url(r'', include('share_site.urls', namespace="site")),
    url(r'', include('reviews.urls', namespace="reviews")),
)

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

share_search/reviews/models.py
from django.db import models


class ReviewModel(models.Model):
    """Abstract class for core review values"""
    body = models.TextField()
    body_markup = models.TextField()
    rating = models.IntegerField(
        choices=(zip(range(1, 6), range(1, 6)))
    )
    votes = models.IntegerField()

    class Meta:
        abstract = True


class ProfileModel(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    description_html = models.TextField()

    class Meta:
        abstract = True


class Store(ProfileModel):
    image = models.ImageField(upload_to="store_profile")

    @models.permalink
    def get_absolute_url(self):
        return ("reviews:store", (self.pk,))


class PhotoModel(models.Model):
    image = models.ImageField(upload_to="profile_photos")
    description = models.TextField()
    store = models.ForeignKey(Store, related_name="photos")


class Product(ProfileModel):
    image = models.ImageField(upload_to="product_profile")

    @models.permalink
    def get_absolute_url(self):
        return ("reviews:product", (self.pk,))


class ProductReview(ReviewModel):
    store = models.ForeignKey(Store, related_name="product_reviews")
    product = models.ForeignKey(Product, related_name="reviews")


class StoreReview(ReviewModel):
    store = models.ForeignKey(Store, related_name="reviews")

share_search/reviews/forms.py
from django import forms

from reviews.models import Store, PhotoModel, Product


class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ("name", "description", "image")


class PhotoForm(forms.ModelForm):
    class Meta:
        model = PhotoModel
        fields = ("description", "image", "store")

        widgets = {
            "store": forms.HiddenInput()
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "description", "image")

share_search/reviews/views.py
from braces.views import LoginRequiredMixin
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import DetailView, ListView, CreateView, UpdateView

from reviews.forms import StoreForm, ProductForm, PhotoForm
from reviews.models import Store, Product, PhotoModel


class StoreDetailView(DetailView):
    model = Store

    def get_context_data(self, *args, **kwargs):
        context = super(StoreDetailView, self).get_context_data(
            *args,
            **kwargs
        )

        context["photo_form"] = PhotoForm()
        return context


class StoreListView(ListView):
    model = Store


class StoreCreateView(LoginRequiredMixin, CreateView):
    model = Store
    form_class = StoreForm


class StoreUpdateView(LoginRequiredMixin, UpdateView):
    model = Store
    form_class = StoreForm


class ProductDetailView(DetailView):
    model = Product


class ProductListView(ListView):
    model = Product


class PhotoModelCreateView(LoginRequiredMixin, CreateView):
    model = PhotoModel
    form_class = PhotoForm

    def get_success_url(self, *args, **kwargs):
        if self.object:
            return reverse("reviews:store", args=(self.object.store.pk,))
        else:
            return reverse(
                "reviews:store",
                args=(self.request.POST.get("store"),)
            )

    def form_invalid(self, form):
        return HttpResponseRedirect(self.get_success_url())


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = StoreForm

share_search/reviews/templates/reviews/photomodel_form.html
{% load crispy_forms_tags %}
{{ form|crispy }}

share_search/reviews/templates/reviews/product_detail.html
{% extends "_layouts/base.html" %}

{% block title %}{{ block.super }} - {{ object.name }}{% endblock %}

{% block content %}
    <div class="row">
        <hgroup class="span12">
            <h1>{{ object.name }}</h1>
            {% if user.is_authenticated %}
                <p>
                    Product details not quite right?
                    <a href="{% url "reviews:product_edit" object.id %}" class="btn btn-inverse">Edit Product</a>
                </p>
            {% endif %}
        </hgroup>
    </div>
    <div class="row">
        <div class="span4">
            <div class="row-fluid">
                <div class="span12">
                    <img src="{{ object.image.url }}">
                </div>
            </div>
        </div>
        <div class="span8">
            {{ object.description }}
        </div>
    </div>
    <div class="row">
        <div class="span12">
            <center>List of stores with the product...</center>
        </div>
    </div>
{% endblock %}

share_search/reviews/templates/reviews/product_form.html
{% extends "_layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="offset4 span4 well">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn" value="{% if object %}Edit{% else %}Create{% endif %} Product">
            </form>
        </div>
    </div>
{% endblock %}

share_search/reviews/templates/reviews/products.html
{% extends "_layouts/base.html" %}
{% load gridify %}

{% block title %} {{ block.super }} - Products{% endblock %}

{% block content %}
    {% if object_list %}
        <div class="row">
            <div class="span9 offset2">
                <h1>{{ object_list.count }} products found</h1>
                {% if user.is_authenticated %}
                    <p>
                        Not seeing the product you're looking for? Add a product now!
                        <a href="{% url "reviews:product_create" %}" class="btn btn-inverse">Add a product</a>
                    </p>
                {% else %}
                    <p>
                        Register now to get started adding products
                        <a href="{% url "site:register" %}" class="btn btn-inverse">Register</a>
                    </p>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <div class="row">
        {% if object_list %}
            {% gridify object_list 3 as grid %}
            <div class="grid">
                {% for row in grid %}
                    <div class="row">
                        <div class="offset2">
                            {% for column in row %}
                                <div class="span3">
                                    <a href="{{ column.get_absolute_url }}">
                                        <img src="{{ column.image.url }}">
                                        <center><a href="{{ column.get_absolute_url }}" class="btn btn-block">{{ column.name }}</a></center>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="offset1 span12">
                <h1>No results found</h1>
                {% if user.is_authenticated %}
                    <p>
                        Not seeing the product you're looking for? Add a product now!
                        <a href="{% url "reviews:product_create" %}" class="btn btn-inverse">Add a product</a>
                    </p>
                {% else %}
                    <p>
                        Register now to get started adding products
                        <a href="{% url "site:register" %}" class="btn btn-inverse">Register</a>
                    </p>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}

share_search/reviews/templates/reviews/store_detail.html
{% extends "_layouts/base.html" %}
{% load gridify %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }} - {{ object.name }}{% endblock %}

{% block content %}
    <div class="row">
        <hgroup class="span12">
            <h1>{{ object.name }}</h1>
            {% if user.is_authenticated %}
                <p>
                    Store details not quite right?
                    <a href="{% url "reviews:store_edit" object.id %}" class="btn btn-inverse">Edit Store</a>
                </p>
            {% endif %}
        </hgroup>
    </div>
    <div class="row">
        <div class="span4">
            <div class="row-fluid">
                <div class="span12">
                    <img src="{{ object.image.url }}">
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <a href="#" class="btn btn-block btn-success">Promote</a>
                </div>
            </div>
        </div>
        <div class="span8">
            {{ object.description }}
        </div>
    </div>
    <div class="row">
        <h1 class="span12">Photo</h1>
    </div>
    {% if object.photos.count %}
    <div class="row">
        <h3 class="span12">
            {% if user.is_authenticated %}<a href="#add-photo" data-toggle="modal">Add a photo</a>{% else %}<a href="{% url "site:register" %}">Register to add a photo.</a>{% endif %}
        </h3>
    </div>
        <div class="gallery">
            {% gridify object.photos.all 4 as photos %}
            {% for row in photos %}
                <div class="row">
                    {% for photo in row %}
                        <div class="span3">
                            <img src="{{ photo.image.url }}">
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    {% else %}
        <div class="row">
            <div class="span12">
                    <h3>No photos. {% if user.is_authenticated %}Care to <a href="#add-photo" data-toggle="modal">add one?</a>{% else %}<a href="{% url "site:register" %}">Register to add one.</a>{% endif %}</h3>
            </div>
        </div>
    {% endif %}
    <div class="modal hide" id="add-photo">
        <div class="modal-header">
            <h2>Add a Photo</h2>
        </div>
        <div class="modal-body">
            <form enctype="multipart/form-data" method="post" action="{% url "reviews:photo_create" %}">
                {% csrf_token %}
                {{ photo_form|crispy }}
                <input type="hidden" name="store" value="{{ object.id }}">
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn" data-dismiss="modal">Nevermind</button>
            <button class="btn btn-primary submit-button" data-dismiss="modal">Add Photo</button>
        </div>
    </div>
{% endblock %}

share_search/reviews/templates/reviews/store_form.html
{% extends "_layouts/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">
        <div class="offset4 span4 well">
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn" value="{% if object %}Edit{% else %}Create{% endif %} Store">
            </form>
        </div>
    </div>
{% endblock %}

share_search/reviews/templates/reviews/store_list.html
{% extends "_layouts/base.html" %}
{% load gridify %}

{% block title %} {{ block.super }} - Stores{% endblock %}

{% block content %}
    {% if object_list %}
        <div class="row">
            <div class="span9 offset2">
                <h1>{{ object_list.count }} stores found</h1>
                {% if user.is_authenticated %}
                    <p>
                        Not seeing the store you're looking for? Add a store now!
                        <a href="{% url "reviews:store_create" %}" class="btn btn-inverse">Add a store</a>
                    </p>
                {% else %}
                    <p>
                        Register now to get started adding stores
                        <a href="{% url "site:register" %}" class="btn btn-inverse">Register</a>
                    </p>
                {% endif %}
            </div>
        </div>
    {% endif %}
    <div class="row">
        {% if object_list %}
            {% gridify object_list 3 as grid %}
            <div class="grid">
                {% for row in grid %}
                    <div class="row">
                        <div class="offset2">
                            {% for column in row %}
                                <div class="span3">
                                    <img src="{{ column.image.url }}">
                                    <a class="btn btn-block" href="{{ column.get_absolute_url }}">
                                        {{ column.name }}
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="offset1 span12">
                <h1>No results found</h1>
                {% if user.is_authenticated %}
                    <p>
                        Not seeing the store you're looking for? Add a store now!
                        <a href="{% url "reviews:store_create" %}" class="btn btn-inverse">Add a store</a>
                    </p>
                {% else %}
                    <p>
                        Register now to get started adding stores
                        <a href="{% url "site:register" %}" class="btn btn-inverse">Register</a>
                    </p>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}